version: '3.8'

services:
    mysql:
        image: mysql:8.0.17
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
    php:
        container_name: ${COMPOSE_PROJECT_NAME}_php
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/app
        ports:
            - "9005:9000"
    nginx:
        image: nginx:stable
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
    mysql_data:
